# Generated by Django 5.1.7 on 2025-03-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Mechanic', 'Mechanic'), ('Storekeeper', 'Storekeeper'), ('Cashier', 'Cashier'), ('Customer', 'Customer')], max_length=30, null=True),
        ),
    ]
