# Generated by Django 5.0.7 on 2025-04-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the business or workshop.', max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo image of the business.', null=True, upload_to='settings/logos/')),
                ('phone_number', models.CharField(blank=True, help_text='Primary contact phone number.', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Primary contact email address.', max_length=254, null=True)),
                ('address', models.TextField(blank=True, help_text='Physical address of the business.', null=True)),
                ('opening_time', models.TimeField(blank=True, help_text='Business opening time.', null=True)),
                ('closing_time', models.TimeField(blank=True, help_text='Business closing time.', null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Applicable tax rate in percentage.', max_digits=5, null=True)),
                ('labor_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Labor rate per hour.', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Application Settings',
                'verbose_name_plural': 'Application Settings',
            },
        ),
    ]
