# Generated by Django 5.0.7 on 2025-03-26 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleNoteProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vehicle_check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.vehiclecheckin')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Note Properties',
            },
        ),
    ]
