# Generated by Django 5.1.7 on 2025-03-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
