# Generated by Django 5.0.7 on 2025-04-06 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_total', models.DecimalField(decimal_places=2, help_text='Total cost of the quotation including parts and labor.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Quotation generation time.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated time.')),
                ('vehicle_solution', models.OneToOneField(help_text='Vehicle solution this quotation is based on.', on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='base.vehiclesolution')),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField(help_text='Quantity of item used in the solution.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price at time of quotation.', max_digits=10)),
                ('item_total', models.DecimalField(decimal_places=2, help_text='Total cost (quantity * unit price).', max_digits=12)),
                ('inventory_item', models.ForeignKey(help_text='Inventory item used.', on_delete=django.db.models.deletion.PROTECT, to='base.inventory')),
                ('quotation', models.ForeignKey(help_text='Quotation this item is part of.', on_delete=django.db.models.deletion.CASCADE, related_name='quoted_items', to='base.quotation')),
            ],
            options={
                'verbose_name': 'Quoted Item',
                'verbose_name_plural': 'Quoted Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuotedMechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_share', models.DecimalField(decimal_places=2, help_text='Calculated labor compensation for this mechanic.', max_digits=10)),
                ('mechanic', models.ForeignKey(help_text='Mechanic assigned to the solution.', limit_choices_to={'role': 'Mechanic'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(help_text='Quotation this mechanic is part of.', on_delete=django.db.models.deletion.CASCADE, related_name='quoted_mechanics', to='base.quotation')),
            ],
            options={
                'verbose_name': 'Quoted Mechanic',
                'verbose_name_plural': 'Quoted Mechanics',
                'ordering': ['id'],
                'unique_together': {('quotation', 'mechanic')},
            },
        ),
    ]
