# Generated by Django 5.1.7 on 2025-03-26 21:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_vehiclecheckin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VehicleCheckIn',
            new_name='VehicleIssue',
        ),
        migrations.AlterModelOptions(
            name='vehicleissue',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Vehicles Issues'},
        ),
    ]
