# Generated by Django 5.0.7 on 2025-04-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_quotation_quoteditem_quotedmechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', help_text='Payment status for this quotation.', max_length=10),
        ),
    ]
