# Generated by Django 5.0.7 on 2025-03-30 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_inventory_quotationitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='vehiclecheckin',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='vehiclecheckin',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehiclenoteproperty',
            name='vehicle_check_in',
        ),
        migrations.RemoveField(
            model_name='vehicleissue',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vehicleissue',
            name='vehicle',
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='plate_number',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(blank=True, help_text='Unique license plate number of the vehicle.', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.CharField(blank=True, help_text='Manufacturer of the vehicle (e.g., Toyota, Ford, etc.).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the vehicle record was last updated.', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, help_text='Vehicle Identification Number (VIN).', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, help_text='Color of the vehicle.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the vehicle record was created.', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='customer',
            field=models.ForeignKey(help_text='The customer who owns the vehicle.', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, help_text='Model of the vehicle (e.g., Camry, F-150, etc.).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Year the vehicle was manufactured.', null=True),
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
        migrations.DeleteModel(
            name='QuotationItem',
        ),
        migrations.DeleteModel(
            name='VehicleCheckIn',
        ),
        migrations.DeleteModel(
            name='VehicleNoteProperty',
        ),
        migrations.DeleteModel(
            name='VehicleIssue',
        ),
    ]
