# Generated by Django 5.0.7 on 2025-04-06 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_quotation_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Exact amount paid.', max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer')], help_text='Method used to make the payment.', max_length=30)),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the payment was made.')),
                ('paid_by', models.ForeignKey(help_text='User who performed the payment.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.OneToOneField(help_text='Quotation that this payment is for.', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='base.quotation')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
