# Generated by Django 5.0.7 on 2025-04-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Applied tax rate (%) at the time of payment.', max_digits=5, null=True),
        ),
    ]
