# Generated by Django 5.0.7 on 2025-03-30 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_quotationitem_quotation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_issue', models.TextField(blank=True, help_text='Description of the issue as reported by the customer.', null=True)),
                ('diagnosed_issue', models.TextField(blank=True, help_text='Diagnosis details provided by a mechanic.', null=True)),
                ('repair_notes', models.TextField(blank=True, help_text='Notes regarding repair work performed on the vehicle.', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', help_text='Current status of the vehicle issue.', max_length=20)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost for the repair work.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the issue was reported.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the issue details were last updated.')),
                ('vehicle', models.ForeignKey(blank=True, help_text='The vehicle that has the reported issue.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='base.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Issue',
                'verbose_name_plural': 'Vehicle Issues',
                'ordering': ['-created_at'],
            },
        ),
    ]
