# Generated by Django 5.0.7 on 2025-03-30 15:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_vehicleissue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_description', models.TextField(help_text='Detailed description of the repair solution provided.')),
                ('solution_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the solution was provided.')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='The total cost incurred for the repair solution.', max_digits=10, null=True)),
                ('vehicle_issue', models.OneToOneField(help_text='The vehicle issue for which this solution is provided.', on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='base.vehicleissue')),
            ],
            options={
                'verbose_name': 'Vehicle Solution',
                'verbose_name_plural': 'Vehicle Solutions',
                'ordering': ['-solution_date'],
            },
        ),
        migrations.CreateModel(
            name='SolutionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField(help_text='The quantity of the inventory item used for the repair.')),
                ('item_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit of the inventory item at the time of usage.', max_digits=10)),
                ('inventory_item', models.ForeignKey(help_text='The inventory item used in the repair.', on_delete=django.db.models.deletion.PROTECT, to='base.inventory')),
                ('vehicle_solution', models.ForeignKey(help_text='The vehicle solution in which the inventory item was used.', on_delete=django.db.models.deletion.CASCADE, related_name='solution_items', to='base.vehiclesolution')),
            ],
            options={
                'verbose_name': 'Solution Item',
                'verbose_name_plural': 'Solution Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleSolutionMechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanic', models.ForeignKey(help_text="The mechanic assigned to the vehicle solution. The user should have a role of 'Mechanic'.", on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vehicle_solution', models.ForeignKey(help_text='The vehicle solution to which this mechanic is assigned.', on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_assignments', to='base.vehiclesolution')),
            ],
            options={
                'verbose_name': 'Vehicle Solution Mechanic',
                'verbose_name_plural': 'Vehicle Solution Mechanics',
                'ordering': ['id'],
                'unique_together': {('vehicle_solution', 'mechanic')},
            },
        ),
    ]
