# Generated by Django 5.0.7 on 2025-05-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_payment_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='stamp_image',
            field=models.ImageField(blank=True, help_text='Official stamp image to be applied on documents and quotations.', null=True, upload_to='settings/stamps/'),
        ),
    ]
