# Generated by Django 5.0.7 on 2025-03-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_inventory_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionitem',
            name='item_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit of the inventory item at the time of usage.', max_digits=10, null=True),
        ),
    ]
